languages: node_js
node_js: '8.0'
php: '5.3'
env:
  global:
  - secure: fvcTDioUhO1lG+16+xdDcbfx5NKkuyEFU3FvfXkAe4N+nUVAgqutT53qr1bI1rMgan6yD7AoVOVa5YjDl6uHRdJAfi1D5kSgHquYwmwZmbafqEVTavM/JnQDOl6bYD38fLfFCYqKkPNUS1ubEDyeFUoJd+2tN3YmQZJyxqsUcOq4kzHavNEQh+cTdD2iQFOEyxJpuHg0eFpDCIU5rGLQndt5ZHROEVkw1qiVokospJpmxd3eK6QP8/Q6BG987g9VkG7qWVBHuvwFR+idy5cX2mVOEkP84uYNfuBfyx6B+rhYCMqINBwa1IBJ8ecW7A6wMOmk2hVYFPaPMgG0DFCU6CNJg738btlBHOrTuMX0uMREwKdZ4N+Y9nlTwlTLk4nv4SYUnT/J2MgRmyv673ilpUekUOf+FNqMwYG7331qxgA2AAkqn5IYr9oeE+YoFvKuF6NwZrT3h1we3J4Um4HPfWaASb0LuiszVkgG+kneakZtAOic4lkvQh+Ox360hH+twpONcCrJdbEOSUn7u+5u4DgVmdS5lSl66EypJ6GHZZfsoiOueIiUQxIAGOmFGNK96biKReSCnLfS9qwZrwfhvy4vNEjeJ5sN2nGHjzOPCee1wL4CazpmP6zpjz+4z/qXrL4u4rs0h7oVu2lhj3ZPxdycd3hTEmvVolmvcFKZrbE=
  - GIT_USER='Jorge Matricali'
  - GIT_EMAIL=jorgematricali@gmail.com
  - GIT_REPO=github.com/jorge-matricali/x3n4.git
before_install:
- git config --global user.name "$GIT_USER"
- git config --global user.email $GIT_EMAIL
- export X3N4_VERSION=$(node -e "console.log(require('./package.json').version);")
install: npm install
before_script:
- npm install -g gulp-cli
script: gulp build
after_success: '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master"
  ] && gulp deploy || false'
deploy:
  provider: releases
  api_key:
    secure: TmnqpJbohpR00yXvc1eaMU9uRSU4D+/1V5lLGqqp45cLvVzUHnxuooR7yZevM+0F90ycjfxPglQwPMMogjp79WyFldEJDr53u+aazV2IaFBESDUFLQGOIby19DEh1QRI9caND0fBI3LXg6fQYAFMMU88SVPvw7Ih6bj0Fpz2YoT+UeH1NTMBDtlH/O6+6BV5TaBR0R+zGmRcxX7MtkDT9TjFbjEVGSYt9lGuYHuZ67wWjk7zvahUK//MPBvyHP08iz3vMoamP43+WRJHhyuZZN/JSbjxi9mB14bX18Doi/O+SVHMpa1GN8drU+dRTOFfu1P8JHTggQ/f48I2xOxFJ1AH1NkFdmFOMVdzWEW9hpvgmdDrOp4PgLAGYpC9vBZlmUQxctdGg+C/H/Vqg2DOezXoEgJOKFSH8jdnGJ0KhDqCk5h4BWDg+U9pkbkhkn3gM0uzg0dbt+n+aZDwY0mAj0H5U2kj6r1hiX1cE1dNNwJVpnGaUkuhpFm+h8avQGstzrVEXdx3xAW7UBdjReSNQNgrHlWschYjqH5e3gaKV3Jz6yPCqB5MHXEPUUqRU6llK9fYDUyNOE61PybLDm2i3x8h0U21oLxEu8zZUdjNOqQErNQ9NIonK59UIRXUNiHicEwN5zILgOs28Twx7HMWR206CKwETRceRuMW1C8jqa4=
  skip_cleanup: true
  file_glob: true
  file: dist/x3n4.php
  on:
    tags: true
    repo: jorge-matricali/x3n4
